### ISSUE TITLE
Automate / re-do how data is converted to geojson

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/drones#13]
currently doing manual joins and upload.

Options:
- use turf.js to do the join
- use CKAN, but need to figure out the lat/lon rounding
- pull from Google Spreadsheets directly, but need to clean up header rows (talk to @pickled-plugins about this -- Peter don't worry about this right now, it's mostly a reminder note for me)

**Comment by sajacy** [comment]
This is resolved by storing the `geometry` field in CKAN.  We rely on the pages / clients to transform the CKAN records into GeoJSON features.  See [map.html](https://github.com/newamericafoundation/drones/blob/6d8705780d661fb61e3545b7dc3bb3525f7abbd1/map.html#L62)
