### ISSUE TITLE
Integrate analytics tied to New America Google Analytics account

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/drones#29]
This may have been done, but since we're not sure at the moment, verifying, and including this for tracking.

**Comment by sajacy** [comment]
There is some GA code I copied from the Drupal pages but I'm not sure if it is actually tracking. Can you check in the GA dashboard?

**Comment by georgiamoon** [comment]
I think @critzo is looking.

On Sat, Jun 13, 2015 at 1:13 PM, Jeffrey Yang <notifications@github.com>
wrote:

> There is some GA code I copied from the Drupal pages but I'm not sure if
> it is actually tracking. Can you check in the GA dashboard?
>
>
> > On Jun 13, 2015, at 10:30, georgia bullen <notifications@github.com>
> wrote:
> >
> > This may have been done, but since we're not sure at the moment,
> verifying, and including this for tracking.
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/newamericafoundation/drones/issues/29#issuecomment-111730781>
> .
>



-- 
Georgia Bullen
Open Technology Institute <http://newamerica.org/oti/> @ New America
<http://newamerica.org>
@georgiamoon <http://twitter.com/georgiamoon>

**Comment by georgiamoon** [comment]
Here's an updated snippet: 

<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-368921-33', 'auto');
  ga('send', 'pageview');

</script>

@sajacy if you get to this before me, just lmk and do a PR.
