### ISSUE TITLE
add keywords to the main page to help the site show up in search

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/drones#31]

**Comment by sajacy** [comment]
Need to know what keywords you'd like to use.  Also - you probably could handle this.  it's just a few `<meta>` tags.

**Comment by kakaes** [comment]
Here's a list to get us started; feel free to add to it if something occurs to any of you that I've forgotten.

UAV, drone, RPAS, RPAV, UAS, drones, remote sensing, imagery, disaster response, drone regulation, FAA, ICAO, New America drone database, unmanned aircraft, RPA, VANT, COA, 333, airplane, property rights, Phantom, DJI, CAA, Transport Canada, CASA, hyperspectral, lidar, Conservation Drones, eBee, Sensefly, DIY Drones
