### ISSUE TITLE
For countries where there is no known regulation, add the text "no known regulations" or something to that effect

### ISSUE THREAD

**Issue by georgiamoon** [newamericafoundation/drones#35]

**Comment by kakaes** [comment]
Be great to do this; not sure what easiest way to implement is? Will depend a bit on how Jeff implements the editing function in CKAN

**Comment by natmey** [comment]
I'm assuming that this is already flagged somewhere in CKan (since we know how to gray out the countries already), so the question is really about picking the standard verbiage and adding it to the display output for those countries.

**Comment by kakaes** [comment]
Good point. Let's use the same text we have in the lower right (which we should also leave there for now, pending a key) and have it display: "No explicit drone regulations known"
